# Generated by Django 5.0.6 on 2026-06-28 06:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=2000)),
                ('depth', models.CharField(choices=[('quick', 'Quick'), ('standard', 'Standard'), ('deep', 'Deep')], default='standard', max_length=16)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUEUED', max_length=16)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True)),
                ('sections', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='research.researchrun')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='processing', max_length=16)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='research_do_user_id_af75f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marker', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('web', 'Web'), ('document', 'Document')], default='web', max_length=16)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('url', models.URLField(blank=True, max_length=1024)),
                ('doc_ref', models.CharField(blank=True, max_length=255)),
                ('snippet', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='research.report')),
            ],
            options={
                'ordering': ['marker'],
                'unique_together': {('report', 'marker')},
            },
        ),
        migrations.AddIndex(
            model_name='researchrun',
            index=models.Index(fields=['user', '-created_at'], name='research_re_user_id_246887_idx'),
        ),
    ]
